### ISSUE TITLE
Can't access https://s3.amazonaws.com/chameleon-heroku-assets...

### ISSUE THREAD

**Issue by palfvin** [nasali/oracle-oci8-heroku-buildpack#4]
I tried running this buildpack on a cloud foundry system (otherwise compatible with Heroku buildpacks) and got the following error:

-----> Downloaded app package (181M)
-----> Downloaded app buildpack cache (139M)
Cloning into '/tmp/buildpacks/heroku-buildpack-multi'...
=====> Downloading Buildpack: https://github.com/nasali/oracle-oci8-heroku-buildpack.git
=====> Detected Framework: Oracle
-----> Found a .oracle.ini
       Making folders...
sh: 2: /: Permission denied
       Downloading and extracting archives from https://s3.amazonaws.com/chameleon-heroku-assets...
sh: 2: /: Permission denied

I then tried to access the aws asset on my browser and got a 403 error. Is this asset only accessible from heroku systems?

**Comment by nasali** [comment]
It looks like the S3 bucket is gone. I don't own it, so I'm not sure what happened.

**Comment by palfvin** [comment]
I misinterpreted the error. The S3 asset is accessible. The permissions error was on the local machine. Sorry for the false alarm.
